# Generated by Django 3.1.5 on 2021-03-30 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210330_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shopping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField()),
                ('summary', models.TextField()),
                ('features', models.BooleanField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
